Start android emulator

diff --git a/.github/workflows/unity.yml b/.github/workflows/unity.yml
--- a/.github/workflows/unity.yml
+++ b/.github/workflows/unity.yml
@@ -60,12 +60,12 @@ jobs:
     - name: Check Results
       run: sed -n 2p unityresults.xml | grep 'result="Passed"'
 
-  playtest-mac-ios-android:
+  playtest-mac-ios:
     name: Run PlayTest unit tests on ${{ matrix.platform }}
     runs-on: pv-ios
     strategy:
       matrix:
-        platform: ['Android', 'StandaloneOSX', 'iOS']
+        platform: ['StandaloneOSX', 'iOS']
 
     steps:
     - uses: actions/checkout@v3
@@ -89,3 +89,43 @@ jobs:
 
     - name: Check Results
       run: sed -n 2p unityresults.xml | grep 'result="Passed"'
+
+  playtest-android:
+    name: Run PlayTest unit tests on ${{ matrix.platform }}
+    runs-on: pv-ios
+    strategy:
+      matrix:
+        platform: ['Android']
+
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: 'recursive'
+
+    - name: Pre-build dependencies
+      run: |
+        ./copy.sh
+        ./copy_test_resources.sh
+
+    - name: Clean conflicting dylib
+      run: rm -rf Assets/Porcupine/Plugins/mac/arm64
+
+    - name: Inject AppID
+      run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
+        Assets/Porcupine/Tests/Integration.cs
+
+    - name: Start Emulator
+      run: /Users/alirezakenarsari-anhari/Library/Android/sdk/emulator -avd Pixel_6_API_33 &
+
+    - name: Run tests
+      run: /Applications/Unity/Hub/Editor/2019.4.34f1/Unity.app/Contents/MacOS/Unity -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform ${{ matrix.platform }} -logFile - || echo "Run potentially failed - checking results anyways"
+
+    - name: Check Results
+      run: sed -n 2p unityresults.xml | grep 'result="Passed"'
+
+    - name: Archive Test Results
+      if: always()
+      uses: actions/upload-artifact@v1
+      with:
+        name: test-results
+        path: app/build
